services:
  Intermediaio\ContaoNewsApi\:
    resource: '../../*'
    exclude: '../../{Entity,Tests,DependencyInjection}'
    autowire: true
    autoconfigure: true

  Intermediaio\ContaoNewsApi\Controller\NewsApiController:
    tags: ['controller.service_arguments']